interview/interview/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

interview/users/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = "users"

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="users:check")),
    path("check/", views.check_phonenumber, name="check"),
    path("login/", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user"),
    path("register/<str:phonenumber>/", views.register_otp, name="register"),
    path("register_info/", views.register_info, name="register_info"),
    path("register_password/", views.register_password, name="register_password"),
]

interview/users/models.py
from django.contrib.auth.models import User
from django.db import models

# from django.db.models.signals import post_save
# from django.dispatch import receiver

# Create your models here.


# class UbaarUserProfile(models.Model):
#     user = models.OneToOneField(to=User, on_delete=models.CASCADE)
#     first_name = models.CharField(max_length=255, blank=True)
#     last_name = models.CharField(max_length=255, blank=True)

#     def __str__(self):
#         return f"{self.first_name} {self.last_name}"


# @receiver(post_save, sender=User)
# def create_ubaaruser_profile(sender, instance, created, **kawrgs):
#     if created:
#         UbaarUserProfile.objects.create(user=instance)

interview/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (AuthenticationForm,
                                       BaseUserCreationForm, UserCreationForm)
from django.core.validators import MinLengthValidator
from django.forms import CharField, Form, ModelForm, SlugField, TextInput

from .validators import phonenumber_validator

user = get_user_model()

phonenumber_field = CharField(
    label="phonenumber",
    max_length=12,
    validators=[phonenumber_validator],
    widget=TextInput(attrs={"type": "tel"}),
)


class PhonenumberForm(Form):
    phonenumber = phonenumber_field


class RegisterForm(UserCreationForm):
    username = phonenumber_field

    class Meta:  # type: ignore
        model = user
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )


class LoginForm(AuthenticationForm):
    username = phonenumber_field

    class Meta:
        model = user
        fields = ("username", "password")


class OTPForm(Form):
    otp = CharField(
        label="otp", max_length=6, validators=[MinLengthValidator(limit_value=6)]
    )
    otp_cache_key = SlugField(label="otp_cache_key", max_length=20)


class RegisterInfoForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True
        self.fields["email"].required = True

    class Meta:
        model = user
        fields = ("first_name", "last_name", "email")


class RegisterPasswordForm(BaseUserCreationForm):
    password2 = None

    class Meta:  # type: ignore
        model = user
        fields = ("password1",)

interview/users/views.py
from secrets import token_urlsafe

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import get_user_model
from django.core.cache import cache
from django.db.models import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse

from .forms import (LoginForm, OTPForm, PhonenumberForm, RegisterForm,
                    RegisterInfoForm, RegisterPasswordForm)
from .otp import generate_random_otp
from .utils import (ban_user_if_necessary, check_is_user_banned,
                    get_ban_remaining_time)

# Create your views here.

auth_user = get_user_model()


def check_phonenumber(request):
    """
    Handle logging in with phonenumber
    """
    # check if the user is already banned or not
    if request.method == "POST":
        form = PhonenumberForm(request.POST)
        if form.is_valid():
            phonenumber = form.cleaned_data.get("phonenumber")
            # check if the user exists
            try:
                user = auth_user.objects.get(username=phonenumber)
                # set username in session
                request.session["username"] = phonenumber
                # if exists, redirect a view that handles login
                # get user's password
                return render(
                    request,
                    "users/login.html",
                    {"form": LoginForm(initial={"username": phonenumber})},
                )
            # if user obj doesn't exist
            except ObjectDoesNotExist:
                # redirect to a register view with the phonenumber and the corresponding cache key
                return HttpResponseRedirect(
                    reverse("users:register", args=[phonenumber])
                )
        # if phonenumber is not valid
        return render(
            request,
            "users/phonenumber.html",
            {"form": form},
        )
    # first of all, show the phonenumber form to get the user's phonenumber
    # check if user is banned, and show user some feedback
    ctx = {"form": PhonenumberForm, "ban_error": []}
    if check_is_user_banned(request.session.get("username")):
        ctx["ban_error"].append("user (phonenumber) already banned")
    if check_is_user_banned(request.META.get("REMOTE_ADDR")):
        ctx["ban_error"].append("ip already banned")
    return render(request, "users/phonenumber.html", ctx)


def logout_user(request):
    """
    Logout user
    """
    if request.method == "POST":
        logout(request)
        return HttpResponseRedirect(reverse("users:check"))
    return HttpResponseRedirect(reverse("users:check"))


def login_user(request):
    """
    Handle login
    """
    username = request.session.get("username")
    user_ip_address = request.META["REMOTE_ADDR"]
    # set ban time remaining to be the greater of banned by ip or banned by username
    # this way, ban period is insured to be at least BAN_PERIOD_MINUTE
    ban_remaining_time = max(
        get_ban_remaining_time(username), get_ban_remaining_time(user_ip_address)
    )
    is_user_banned = bool(ban_remaining_time)
    if request.method == "POST":
        # first check whether the user is banned or not
        username = request.POST.get("username")
        if is_user_banned:
            # if user is already banned
            return render(
                request,
                "users/login.html",
                {
                    "form": LoginForm,
                    "ban_error": f"user is banned for {ban_remaining_time} minutes",
                },
            )
        # user is posting to this view and not banned
        form = LoginForm(data=request.POST)
        if form.is_valid():
            # then authenticate the user
            user = authenticate(
                username=form.cleaned_data.get("username"),
                password=form.cleaned_data.get("password"),
            )
            if user:
                # if authenticated, login
                login(request, form.get_user())
                # clear the cache used in login attempts
                cache.delete(username)
                return render(request, "users/success.html")
            else:
                # user obj might be None due to user not registered
                return render(
                    request,
                    "users/login.html",
                    {
                        "form": form,
                        "user_error": "user not logged in and/or user doesn't exist",
                    },
                )
        else:
            ctx = {"form": form}
            # check conditions separately
            is_user_banned_by_username = ban_user_if_necessary(username)
            is_user_banned_by_ip = ban_user_if_necessary(user_ip_address)
            is_user_banned = is_user_banned_by_username or is_user_banned_by_ip
            ban_remaining_time = max(
                get_ban_remaining_time(username),
                get_ban_remaining_time(user_ip_address),
            )
            if is_user_banned:
                return HttpResponseRedirect(reverse("users:check"))

            return render(request, "users/login.html", ctx)
    # if user redirected to this view from another view since the user exists
    # check whether the user is banned or not
    if is_user_banned:
        return HttpResponseRedirect(reverse("users:check"))

    # on a get request, just render the form
    return render(request, "users/login.html", {"form": LoginForm})


def register_otp(request, phonenumber):
    """
    Handle registration
    """
    user_ip_address = request.META["REMOTE_ADDR"]
    ban_remaining_time = max(
        get_ban_remaining_time(phonenumber), get_ban_remaining_time(user_ip_address)
    )
    is_user_banned = bool(ban_remaining_time)
    # user has been redirected to get registered
    if request.method == "GET":
        # first check whether the user is banned
        # if banned don't proceed and return with an error
        if is_user_banned:
            # redirect to the check_user_phonenumber view
            return HttpResponseRedirect(reverse("users:check"))
        # initiate an otp process
        # create a random 6 digit string
        random_otp = generate_random_otp()
        print(f"🔴🟢   {random_otp = }")
        # store the otp in cache
        # generate a url_safe token as cache key, reason being it can be sent back as post and cannot be guessed
        otp_cache_key = token_urlsafe(20)[:20]
        # save it in cache
        cache.set(otp_cache_key, random_otp)
        return render(
            request,
            "users/register.html",
            {"form": OTPForm(initial={"otp_cache_key": otp_cache_key})},
        )
    if request.method == "POST":
        # check whether the user is already banned or not (same as GET)
        # but redirect to check_user_phonenumber view instead
        if is_user_banned:
            return HttpResponseRedirect(reverse("users:check"))
        # user is registering with opt value and an implicit otp_cache_key
        # populate the otp form
        form = OTPForm(request.POST)
        if form.is_valid():
            # if otp and cache_key validations pass
            # check whether otp value is correct
            # get user's otp value
            user_otp_value = form.cleaned_data.get("otp")
            # retrieve otp value from cache
            otp_cache_key = form.cleaned_data.get("otp_cache_key")
            server_otp_value = cache.get(otp_cache_key)
            if user_otp_value == server_otp_value:
                # proceed with registration process
                # clear the cache used in otp attempts
                cache.delete(phonenumber)
                # pass phonenumber as session, so that the user can be created with all
                # the gathered info in subsequent views at the last step
                request.session["username"] = phonenumber
                return HttpResponseRedirect(reverse("users:register_info"))
            else:
                # the same as login, but already use url arg (phonenumber) as identifier instead
                # getting value off of session
                ctx = {"form": form}
                ctx = {
                    "form": form,
                    "otp_error": "otp doesn't match",
                }
                # check ban conditions (separably)
                is_user_banned_by_username = ban_user_if_necessary(phonenumber)
                is_user_banned_by_ip = ban_user_if_necessary(user_ip_address)
                is_user_banned = is_user_banned_by_username or is_user_banned_by_ip
                ban_remaining_time = max(
                    get_ban_remaining_time(phonenumber),
                    get_ban_remaining_time(user_ip_address),
                )
                if is_user_banned:
                    return HttpResponseRedirect(reverse("users:check"))

                return render(request, "users/register.html", ctx)

        # if otp form validation doesn't pass
        return render(
            request,
            "users/register.html",
            {"form": form},
        )


def register_info(request):
    """
    Register user info, first name, last name and email
    """
    if request.method == "POST":
        form = RegisterInfoForm(request.POST)
        if form.is_valid():
            # if user entered correct format of the data, proceed to password form
            # update session first
            request.session["first_name"] = form.cleaned_data.get("first_name")
            request.session["last_name"] = form.cleaned_data.get("last_name")
            request.session["email"] = form.cleaned_data.get("email")
            return HttpResponseRedirect(reverse("users:register_password"))

    # if user is redirected here
    # check whether user is redirected with a phonenumber
    if request.session.get("username"):
        # render info entry form

interview/users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Interview Assignment</title>
        <style>
      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
      }
      .site-header {
        background-color: #f8f9fa;
        padding: 20px;
        border-bottom: 1px solid #e0e0e0;
      }
      .site-navigation {
        margin-top: 10px;
      }
      .nav {
        padding: 0;
        display: flex;
        justify-content: space-between;
        align-items: center;
      }
      .btn-list {
        display: flex;
        gap: 10px;
      }
      .logout-btn {
        background-color: red;
        color: black;
        font-weight: bold;
      }
      main {
        margin-top: 100px;
        display: flex;
        flex-direction: column;
        margin-left: auto;
      }
      main * {
        margin-left: auto;
        margin-right: auto;
        margin-top: 10px;
      }
      main input {
        width: 100%;
        text-align: center;
      }
      .errorlist {
        width: 350px;
        color: red;
        font-weight: bold;
        text-wrap: wrap;
      }
      
        </style>
    </head>
    <body>
        <header class="site-header">
            <nav class="site-navigation">
                <div class="nav">
                    {% block debug %}{% endblock %}
                    <div>
                        <p style="margin-bottom: 10px;">current logged in user: {{ request.user }}</p>
                        <p>ip: {{ request.META.REMOTE_ADDR }}</p>
                        <div class="btn-list">
                            <button>
                                <a href="{% url 'users:check' %}">Home</a>
                            </button>
                            {% if request.user.is_authenticated %}
                                <form action="{% url 'users:logout_user' %}" method="post">
                                    {% csrf_token %}
                                    <input class="logout-btn" type="submit" value="logout">
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main>
            {% block content %}{% endblock %}
        </main>
    </body>
</html>

interview/users/templates/users/login.html
{% extends 'users/base.html' %}
{% block debug %}<h1>login form</h1>{% endblock %}
{% block content %}
    <form action="{% url 'users:login_user' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="login">
    </form>
    {% if ban_error %}<p class="errorlist">{{ ban_error }}</p>{% endif %}
    {% if user_error %}<p class="errorlist">{{ user_error }}</p>{% endif %}
{% endblock %}

interview/users/templates/users/phonenumber.html
{% extends 'users/base.html' %}
{% block debug %}<h1>Phonenumber Form</h1>{% endblock %}
{% block content %}
    <form action="{% url 'users:check' %}" method="post">
        {% csrf_token %}
        <h3>Enter phonenumber</h3>
        {{ form.as_p }}
        <input type="submit" value="login">
    </form>
    {% for err in ban_error %}<p class="errorlist">{{ err }}</p>{% endfor %}
{% endblock %}

interview/users/templates/users/register.html
{% extends 'users/base.html' %}
{% block debug %}<h1>register form</h1>{% endblock %}
{% block content %}
    <form method='post'>
        {% csrf_token %}
        <label for="{{ form.otp.id_for_label }}">{{ form.otp.label }}:</label>
        {{ form.otp }}
        {{ form.otp_cache_key.as_hidden }}
        <input type="submit" value="register">
    </form>
    <p>{{ otp_error }}</p>
    <p>{{ ban_error }}</p>
{% endblock %}

interview/users/templates/users/register_info.html
{% extends 'users/base.html' %}
{% block debug %}<h1>register info form</h1>{% endblock %}
{% block content %}
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Next">
    </form>
{% endblock %}

interview/users/templates/users/register_password.html
{% extends 'users/base.html' %}
{% block debug %}<h1>register password form</h1>{% endblock %}
{% block content %}
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

interview/users/templates/users/success.html
{% extends 'users/base.html' %}
{% block debug %}
<h1>Success Page</h1>
{% endblock %}

{% block content %}
<h1>Successfully logged in</h1>
<h3>current logged in user: {{request.user}}</h3>
{% endblock %}